parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_name: packagist
    database_user: root
    database_password:
    database_name_test: packagist_test

    mailer_transport:
    mailer_host: localhost
    mailer_user:
    mailer_password:
    mailer_from_email: admin@example.org
    mailer_from_name: Admin Team

    # packagist_host: example.org
    # router.request_context.host: '%packagist_host%'
    # router.request_context.scheme: https

    redis_dsn: redis://localhost/1
    redis_dsn_test: redis://127.0.0.1/14
    redis_session_dsn: redis://localhost/2

    solr_host: 127.0.0.1
    solr_port: 8983
    solr_path: /solr
    solr_core: collection1

    locale: en

    google_analytics:
        ga_key:

    github.client_id: CHANGE_ME_IN_PROD
    github.client_secret: CHANGE_ME_IN_PROD

    validation_cache_backend: ~
    doctrine_cache_backend: array

    secret: CHANGE_ME_IN_PROD
    remember_me.secret: CHANGE_ME_IN_PROD

    force_ssl: false
    trusted_proxies: ~
    trusted_hosts: ~